export const COLORS = {
  DEFAULT_PRIMARY_COLOR: "#0b1423",
  DEFAULT_PRIMARY_COLOR_LIGHT: "#eaeaea",
  DEFAULT_SECONDARY_COLOR: "#fff",
  APP_PRIMARY_COLOR: "#fd9e44",
  APP_PRIMARY_COLOR_LIGHT: "#f9e8cf",
  BG_DISABLE: "#f7f7f7",
  TEXT_DISABLE: "#aaadb1",
};
